version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpass
      - MONGO_INITDB_DATABASE=testdb

volumes:
  mongodb_data:
